# Generated by Django 3.0.4 on 2020-03-28 01:57

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=tinymce.models.HTMLField(default=0),
            preserve_default=False,
        ),
    ]
