# Generated by Django 3.0.4 on 2020-03-29 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.CharField(default='Description', max_length=400),
            preserve_default=False,
        ),
    ]
