# Generated by Django 3.0.4 on 2020-03-28 04:15

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200328_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
